version: '2'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    ports:
      - '80'
      - '443'
      - '22'
    volumes:
      - './volumes/gitlab/config:/etc/gitlab'
      - './volumes/gitlab/logs:/var/log/gitlab'
      - './volumes/gitlab/data:/var/opt/gitlab'
    environment:
      - GITLAB_ROOT_PASSWORD=12345678
      - GITLAB_HOST=http://gitlab'
    networks:
      le_net:
        ipv4_address: 10.5.0.10
networks:
  le_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
